// Catálogo de exemplo para testar o fluxo sem depender da Google Sheet.
// Ativado com USE_SAMPLE_CATALOG=true (ver lib/google-sheets.ts).
import type { Product } from "@/types";

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "gel-limpeza",
    nome: "Gel de Limpeza Facial",
    descricao: "Limpa sem ressecar, controla a oleosidade.",
    categoria: "Skincare",
    preco: 45.9,
    necessidades: ["oleosidade", "acne"],
    ativo: true,
  },
  {
    id: "serum-vit-c",
    nome: "Sérum Vitamina C",
    descricao: "Ilumina e uniformiza o tom da pele.",
    categoria: "Skincare",
    preco: 89.9,
    necessidades: ["antiidade", "hidratacao"],
    ativo: true,
  },
  {
    id: "hidratante-facial",
    nome: "Hidratante Facial",
    descricao: "Hidratação leve para o dia a dia.",
    categoria: "Skincare",
    preco: 59.9,
    necessidades: ["hidratacao"],
    ativo: true,
  },
  {
    id: "protetor-solar",
    nome: "Protetor Solar FPS 50",
    descricao: "Proteção diária com toque seco.",
    categoria: "Skincare",
    preco: 74.9,
    necessidades: ["protecao-solar", "oleosidade"],
    ativo: true,
  },
  {
    id: "tratamento-acne",
    nome: "Gel Secativo Anti-acne",
    descricao: "Reduz espinhas durante a noite.",
    categoria: "Skincare",
    preco: 39.9,
    necessidades: ["acne"],
    ativo: true,
  },
  {
    id: "base-liquida",
    nome: "Base Líquida Matte",
    descricao: "Cobertura natural com acabamento matte.",
    categoria: "Makeup",
    preco: 69.9,
    necessidades: ["maquiagem"],
    ativo: true,
  },
  {
    id: "batom",
    nome: "Batom Hidratante",
    descricao: "Cor intensa com toque cremoso.",
    categoria: "Makeup",
    preco: 34.9,
    necessidades: ["maquiagem"],
    ativo: true,
  },
  {
    id: "mascara-capilar",
    nome: "Máscara de Reconstrução Capilar",
    descricao: "Repara e dá brilho aos fios.",
    categoria: "Cabelo",
    preco: 54.9,
    necessidades: ["cabelos"],
    ativo: true,
  },
  {
    id: "perfume-floral",
    nome: "Perfume Floral 50ml",
    descricao: "Fragrância marcante e duradoura.",
    categoria: "Perfumaria",
    preco: 129.9,
    necessidades: ["perfumaria"],
    ativo: true,
  },
];
